import { prisma } from "@/lib/db";

export default async function DashboardPage() {
  const [participantCount, recentBatches, recentReports] = await Promise.all([
    prisma.participant.count({ where: { isActive: true } }),
    prisma.importBatch.findMany({
      orderBy: { createdAt: "desc" },
      take: 5,
      include: { admin: { select: { name: true } } },
    }),
    prisma.monthlyReport.findMany({
      orderBy: { generatedAt: "desc" },
      take: 5,
      include: { admin: { select: { name: true } } },
    }),
  ]);

  return (
    <div>
      <h2 className="text-2xl font-bold text-gray-900">Dashboard</h2>

      <div className="mt-6 grid grid-cols-1 gap-6 sm:grid-cols-3">
        <div className="rounded-lg border border-gray-200 bg-white p-6">
          <p className="text-sm font-medium text-gray-500">
            Active Participants
          </p>
          <p className="mt-2 text-3xl font-bold text-gray-900">
            {participantCount}
          </p>
        </div>
        <div className="rounded-lg border border-gray-200 bg-white p-6">
          <p className="text-sm font-medium text-gray-500">CSV Imports</p>
          <p className="mt-2 text-3xl font-bold text-gray-900">
            {recentBatches.length > 0 ? recentBatches[0].month : "None"}
          </p>
          <p className="text-sm text-gray-400">Latest import</p>
        </div>
        <div className="rounded-lg border border-gray-200 bg-white p-6">
          <p className="text-sm font-medium text-gray-500">Reports Generated</p>
          <p className="mt-2 text-3xl font-bold text-gray-900">
            {recentReports.length}
          </p>
        </div>
      </div>

      <div className="mt-8 grid grid-cols-1 gap-6 lg:grid-cols-2">
        <div className="rounded-lg border border-gray-200 bg-white p-6">
          <h3 className="text-lg font-semibold text-gray-900">
            Recent Imports
          </h3>
          {recentBatches.length === 0 ? (
            <p className="mt-4 text-sm text-gray-500">
              No imports yet. Upload a CSV from the Attendance page.
            </p>
          ) : (
            <table className="mt-4 w-full text-sm">
              <thead>
                <tr className="border-b text-left text-gray-500">
                  <th className="pb-2">Month</th>
                  <th className="pb-2">File</th>
                  <th className="pb-2">Records</th>
                  <th className="pb-2">Date</th>
                </tr>
              </thead>
              <tbody>
                {recentBatches.map((batch) => (
                  <tr key={batch.id} className="border-b last:border-0">
                    <td className="py-2">{batch.month}</td>
                    <td className="py-2 text-gray-600">{batch.filename}</td>
                    <td className="py-2">{batch.recordCount}</td>
                    <td className="py-2 text-gray-500">
                      {batch.createdAt.toLocaleDateString()}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>

        <div className="rounded-lg border border-gray-200 bg-white p-6">
          <h3 className="text-lg font-semibold text-gray-900">
            Recent Reports
          </h3>
          {recentReports.length === 0 ? (
            <p className="mt-4 text-sm text-gray-500">
              No reports yet. Generate one from the Reports page.
            </p>
          ) : (
            <table className="mt-4 w-full text-sm">
              <thead>
                <tr className="border-b text-left text-gray-500">
                  <th className="pb-2">Month</th>
                  <th className="pb-2">Generated by</th>
                  <th className="pb-2">Date</th>
                </tr>
              </thead>
              <tbody>
                {recentReports.map((report) => (
                  <tr key={report.id} className="border-b last:border-0">
                    <td className="py-2 font-medium">{report.month}</td>
                    <td className="py-2 text-gray-600">{report.admin.name}</td>
                    <td className="py-2 text-gray-500">
                      {report.generatedAt.toLocaleDateString()}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      </div>
    </div>
  );
}
